### ISSUE TITLE
Event Create

### ISSUE THREAD

**Issue by prononext** [that-one-tom/n8n-nodes-caldav#1]
Are there any plans to use the node to create events via CalDAV?

**Comment by that-one-tom** [comment]
HI @prononext, I am afraid not. I've built this node for notification purposes (query my calendar every couple minutes, then display the next event on an [awtrix-light](https://github.com/Blueforcer/awtrix-light)-powered clock and don't have any in-depth knowledge about the CalDAV protocol that would allow me to handle event creation properly.

Sorry :(
